#https://paragonwiki.com/wiki/List_of_Key_Names
KEY_NAMES = [
   #(Primary Name, Secondary Name, Description)
    ('A', '', 'alphabet keys'),
    ('B', '', 'alphabet keys'),
    ('C', '', 'alphabet keys'),
    ('D', '', 'alphabet keys'),
    ('E', '', 'alphabet keys'),
    ('F', '', 'alphabet keys'),
    ('G', '', 'alphabet keys'),
    ('H', '', 'alphabet keys'),
    ('I', '', 'alphabet keys'),
    ('J', '', 'alphabet keys'),
    ('K', '', 'alphabet keys'),
    ('L', '', 'alphabet keys'),
    ('M', '', 'alphabet keys'),
    ('N', '', 'alphabet keys'),
    ('O', '', 'alphabet keys'),
    ('P', '', 'alphabet keys'),
    ('W', '', 'alphabet keys'),
    ('R', '', 'alphabet keys'),
    ('S', '', 'alphabet keys'),
    ('T', '', 'alphabet keys'),
    ('U', '', 'alphabet keys'),
    ('V', '', 'alphabet keys'),
    ('W', '', 'alphabet keys'),
    ('X', '', 'alphabet keys'),
    ('Y', '', 'alphabet keys'),
    ('Z', '', 'alphabet keys'),
    ('F1', '', '"F keys" at the top of the keyboard'),
    ('F2', '', '"F keys" at the top of the keyboard'),
    ('F3', '', '"F keys" at the top of the keyboard'),
    ('F4', '', '"F keys" at the top of the keyboard'),
    ('F5', '', '"F keys" at the top of the keyboard'),
    ('F6', '', '"F keys" at the top of the keyboard'),
    ('F7', '', '"F keys" at the top of the keyboard'),
    ('F8', '', '"F keys" at the top of the keyboard'),
    ('F9', '', '"F keys" at the top of the keyboard'),
    ('F10', '', '"F keys" at the top of the keyboard'),
    ('F11', '', '"F keys" at the top of the keyboard'),
    ('F12', '', '"F keys" at the top of the keyboard'),
    ('ESC', '', 'the Escape key'),
    ('0', '', 'the numbers row near the top of the keyboard'),
    ('1', '', 'the numbers row near the top of the keyboard'),
    ('2', '', 'the numbers row near the top of the keyboard'),
    ('3', '', 'the numbers row near the top of the keyboard'),
    ('4', '', 'the numbers row near the top of the keyboard'),
    ('5', '', 'the numbers row near the top of the keyboard'),
    ('6', '', 'the numbers row near the top of the keyboard'),
    ('7', '', 'the numbers row near the top of the keyboard'),
    ('8', '', 'the numbers row near the top of the keyboard'),
    ('9', '', 'the numbers row near the top of the keyboard'),
    ('-', 'MINUS', 'the (–) key on the numbers row of the keyboard'),
    ('EQUALS', '', 'the (=) and (+) key on the numbers row of the keyboard'),
    ('TILDE', '', 'the (`) and (~) key, on the numbers row of the keyboard'),
    ('BACKSPACE', '', ''),
    ('TAB', '', ''),
    ('[', 'LBRACKET', ''),
    (']', 'RBRACKET', ''),
    ('\\', 'BACKSLASH', ''),
    ('CAPITAL', '', 'the Caps Lock key'),
    (';', 'SEMICOLON', ''),
    ('\'', 'APOSTROPHE', ''),
    ('COMMA', '', 'the comma (,) key'),
    ('.', 'PERIOD', ''),
    ('/', 'SLASH', ''),
    ('SPACE', '', 'the space bar'),
    ('APPS', '', 'the Application Menu key (if your keyboard has it, it would be right next to the right CTRL key)'),
    ('SYSRQ', '', 'the print screen button'),
    ('SCROLL', '', 'the Scroll Lock key'),
    ('PAUSE', '', 'the Pause/Break button'),
    ('INSERT', '', ''),
    ('DELETE', '', ''),
    ('HOME', '', ''),
    ('END', '', ''),
    ('PAGEUP', '', ''),
    ('PAGEDOWN', '', ''),
    ('UPARROW', 'UP', 'the up arrow button'),
    ('DOWNARROW', 'DOWN', 'the down arrow button'),
    ('LEFTARROW', 'LEFT', 'the left arrow button'),
    ('RIGHTARROW', 'RIGHT', 'the right arrow button'),
    ('LSHIFT', '', 'left shift key. When used as a Chord, turns into SHIFT'),
    ('RSHIFT', '', 'right shift key. When used as a Chord, turns into SHIFT'),
    ('LALT', '', 'left ALT key. When used as a Chord, turns into ALT'),
    ('RALT', '', 'right ALT key. When used as a Chord, turns into ALT'),
    ('LCONTROL', 'LCTRL', 'left CTRL key. When used as a Chord, turns into CTRL'),
    ('RCONTROL', 'RCTRL', 'right CTRL key. When used as a Chord, turns into CTRL'),
    ('NUMPAD0', '', 'the "0" key on the Number Pad'),
    ('NUMPAD1', '', 'the "1" key on the Number Pad'),
    ('NUMPAD2', '', 'the "2" key on the Number Pad'),
    ('NUMPAD3', '', 'the "3" key on the Number Pad'),
    ('NUMPAD4', '', 'the "4" key on the Number Pad'),
    ('NUMPAD5', '', 'the "5" key on the Number Pad'),
    ('NUMPAD6', '', 'the "6" key on the Number Pad'),
    ('NUMPAD7', '', 'the "7" key on the Number Pad'),
    ('NUMPAD8', '', 'the "8" key on the Number Pad'),
    ('NUMPAD9', '', 'the "9" key on the Number Pad'),
    ('NUMLOCK', '', 'the Number Lock key on the Number Pad'),
    ('DIVIDE', '', 'the (/) key on the Number Pad'),
    ('MULTIPLY', '', 'the (*) key on the Number Pad'),
    ('SUBTRACT', '', 'the (-) key on the Number Pad'),
    ('ADD', '', 'the (+) key on the Number Pad'),
    ('DECIMAL', '', 'the (.) or period on the Number Pad'),
    ('NUMPADENTER', '', 'the Enter key on the Number Pad'),
    ('LBUTTON', '', 'left mouse button'),
    ('RBUTTON', '', 'right mouse button'),
    ('MBUTTON', '', 'middle mouse button (for some mice, the mouse wheel also acts as a middle button)'),
    ('BUTTON4', '', 'usually a thumb button'),
    ('BUTTON5', '', ''),
    ('BUTTON6', '', ''),
    ('BUTTON7', '', ''),
    ('BUTTON8', '', ''),
    ('MOUSECHORD', '', 'mouse chord key - both the left and right mouse buttons pressed at the same time'),
    ('MOUSEWHEEL', '', 'By default is bound to the "+camdistadjust" command. But can be used for other commands (e.g. target_next_enemy)'),
    ('JOYPAD_DOWN', '', 'Directional Pad'),
    ('JOYPAD_LEFT', '', 'Directional Pad'),
    ('JOYPAD_RIGHT', '', 'Directional Pad'),
    ('JOYPAD_UP', '', 'Directional Pad'),
    ('JOYSTICK1_DOWN', '', 'Left Analog Stick'),
    ('JOYSTICK1_LEFT', '', 'Left Analog Stick'),
    ('JOYSTICK1_RIGHT', '', 'Left Analog Stick'),
    ('JOYSTICK1_UP', '', 'Left Analog Stick'),
    ('(click/depress) JOY9', '', 'Left Analog Stick'),
    ('(click/depress) JOY10', '', 'Right Analog Stick'),
    ('JOYSTICK3_RIGHT', '', 'Left Trigger'),
    ('JOYSTICK3_LEFT', '', 'Right Trigger'),
    ('JOY5', '', 'Left Bumper'),
    ('JOY6', '', 'Right Bumper'),
    ('JOY1', '', 'A Button'),
    ('JOY2', '', 'B Button'),
    ('JOY3', '', 'X Button'),
    ('JOY4', '', 'Y Button'),
    ('JOY7', '', 'Back Button'),
    ('JOY8', '', 'Start Button')
]

CHORD_KEYS = [
    ('SHIFT', '', 'assigns both the left and right Shift keys'),
    ('ALT', '', 'assigns both the left and right ALT keys'),
    ('CONTROL', 'CTRL', 'assigns both the left and right CTRL keys'),
]