#https://paragonwiki.com/wiki/List_of_Slash_Commands
LIST_OF_SLASH_COMMANDS = [
    #(command, 'target', description)
    ('ac',  'message', 'Alias for /arena'),
    ('afk',  'message', 'Marks the player as Away From Keyboard (with given message)'),
    ('ah',  '', 'Activate the Auction House Menu Alias: /auctionhouse'),
    ('ai',  'player', 'Alias for /arena_invite'),
    ('alttray',  '', 'Toggle the secondary tray while a key is being pressed (for keybinds)'),
    ('alt2tray',  '', 'Toggle the tertiary tray while a key is being pressed (for keybinds)'),
    ('alttraysticky',  '', 'Toggle the secondary tray'),
    ('architect',  '', 'Activates the Architect Entertainment mission search menu'),
    ('architect_claim_tickets',  '#', 'Claims # Architect tickets'),
    ('architect_invisible',  '', 'Toggles Architect test mode invisibility on or off'),
    ('architect_invincible',  '', 'Toggles Architect test mode invincibility on or off'),
    ('architect_completemission',  '', 'Completes the current mission being tested'),
    ('architect_nextobjective',  '', 'Takes you to the next objective in the mission being tested'),
    ('architect_nextcritter',  '', 'Takes you to the next hostile entity in the mission being tested'),
    ('architect_killtarget',  '', 'Defeats your currently selected target in the mission being tested'),
    ('architect_loginupdate',  '', 'Shows amount of Architect tickets available to claim'),
    ('arena',  'message', 'Sends the specified message on the arena chat channel. Alias: /ac'),
    ('arena_invite',  'player', 'Invite player to join your arena event. Alias: /ai'),
    ('arenalist',  '', 'Open the arena window from anywhere in the game'),
    ('assist',  '', 'Change your current target to selected ally\'s or enemy\'s target'),
    ('assist_name',  'player', 'Change your current target to specified ally\'s target'),
    ('auction',  'message', 'Send message to Auction channel'),
    ('auctionhouse',  '', 'Activate the Auction House Menu'),
    ('autoperf',  '', 'Automatically change world detail for performance'),
    ('autoreply',  '', 'Start a reply for client'),
    ('autorun',  '', 'Toggles autorun'),
    ('b',  'message', 'Alias for /broadcast'),
    ('backward',  '', 'Move backwards'),
    ('beginchat',  '', 'Starts chat-entry mode with given string'),
    ('bind_load_file',  'filename', 'Reads a list of keybinds from a file'),
    ('bind_load_file_silent',  'filename', 'Same as bind_load_file but does not display confirmation message'),
    ('bind_load',  '', 'Reads a list of keybinds from COH_INSTALL_DIRECTORY\\keybinds.txt'),
    ('bind_save_file',  'filename', 'Saves all keybinds to specified file'),
    ('bind_save_file_silent',  'filename', 'Same as bind_save_file but does not display confirmation message'),
    ('bind_save',  '', 'Saves all keybinds to COH_INSTALL_DIRECTORY\\keybinds.txt'),
    ('bind',  'key command', 'Binds a key to a command or group of commands'),
    ('blackmarket',  '', 'Activate the Auction House Menu Alias: /auctionhouse'),
    ('bloomscale',  'number', 'Sets bloom blur scale, valid values are 2 and 4'),
    ('bloomweight',  'number', 'Sets bloom scale, valid values 0.0 - 2.0'),
    ('broadcast',  'message', 'Send message to Broadcast channel. Aliases: /b, /y, /yell'),
    ('buffs',  '', 'Toggle team buff display'),
    ('bug',  'subject', 'Report a Bug'),
    ('buy_coh',  '', 'Open the buy coh dialog box. Could be used as a method of returning to the title screen without having to sit through the 30 second timer. Was disabled in Issue 21.'),
    ('c',  'message', 'Send message on the Coalition channel (Also: coalition)'),
    ('camdist',  'distance', 'Sets the distance in feet that the third person camera pulls back behind the player'),
    ('camdistadjust', '', 'Adjusts the distance that the third person camera pulls back behind the player.  +camdistadjust by default is bound to the ScrollWheel.'),
    ('camreset',  '', 'Camreset is bound to the PageDown key (default) to reset the camera behind the player'),
    ('camrotate',  '', 'Camrotate is bound to the PageUp key to allow controlled camera rotation around the player This command should not be invoked through the console!'),
    ('camturn',  '', 'Turn camera to match player'),
    ('canlook',  '', 'Whether the player can use the mouse to look around'),
    ('cc',  'slot', 'Change costume to specified costume slot (0-4) (Also: costume_change)'),
    ('cce',  'slot ccemote', 'Change costume to specified costume slot (0-4) using specified emote prefixed with \'cc\' (Also: cc_emote)'),
    ('cc_emote',  'slot ccemote', 'Change costume to specified costume slot (0-4) using specified emote prefixed with \'cc\' (Also: cce)'),
    ('cgShaderPath',  'path', 'Parent directory for "shaders/cgfx". If relative, path is resolved using the .exe directory.'),
    ('chan_create',  'channel', 'Create a new chat channel'),
    ('chan_desc',  'channel description', 'Set the channel\'s description'),
    ('chan_invite',  'channel username', 'Invite a player or chat handle to a chat channel. Alias: /ginvite'),
    ('chan_invite_gf',  'channel', 'Invites your entire global friends list to a global chat channel'),
    ('chan_invite_sg',  'channel rank', 'Invite your entire Supergroup to a global chat channel. Only leaders may use this command. The rank parameter may be any of the ranks listed below. Alias: /ginvite_sg. 0-entire supergroup, 1 captains and leaders only, 2 leaders only'),
    ('chan_invite_team',  'channel', 'Invites your entire team or Task Force to a Global chat channel'),
    ('chan_join',  'channel', 'Join an existing chat channel'),
    ('chan_leave',  'channel', 'Leave a chat channel'),
    ('chan_members',  'channel', 'List all members of channel'),
    ('chan_mode',  'channel options', 'Changes default access rights for new user who joins the channel. If you set -join, no one can join unless invited by an operator.+join / -join, Allows/disallows users from joining the channel +send / -send, Gives/removes user ability to send messages to channel +operator / -operator, Gives/removes operator status from another user in the channel'),
    ('chan_motd',  'channel message', 'Set the channel\'s Message Of The Day, which is sent to everyone that joins or logs into the channel'),
    ('chan_send',  'channel message', 'Send message to chat channel. You must be in the channel and have Send priviledges. (Also: send)'),
    ('chan_user_mode',  'channel global options', 'Sets user permissions for the user with the handle global (without the @) on channel. You must have operator status to set permissions. -join, Kicks user from channel +send / -send Gives/removes user ability to send messages to channel, +operator / -operator Gives/removes operator status to user in the channel'),
    ('chan_timeout',  '<channel name> <days>', 'Sets the number of days a member of a global channel must go without logging in before being automatically kicked from the channel.'),
    ('change_handle',  'new_global', 'Change your global user name, if allowed.'),
    ('chat_cycle',  '', 'Cycles through the default chat channels'),
    ('chat_load',  '', 'Reads a list of chat settings from COH_INSTALL_DIRECTORY\\chat.txt'),
    ('chat_load_file',  'filename', 'Reads a list of chat settings from a file'),
    ('chat_save',  '', 'Saves a list of chat settings to COH_INSTALL_DIRECTORY\\chat.txt'),
    ('chat_save_file',  'filename', 'Saves a list of chat settings to a file'),
    ('chat_set',  'string', 'Sets the channel to the given string'),
    ('chat',  '', 'Toggles the chat window'),
    ('chatoptions',  'window', 'Toggles chat options for specified window (0-4)'),
    ('ci',  'player', 'Alias for /coalition_invite'),
    ('clearchat',  '', 'Clear all chat buffers'),
    ('cleartray',  '', 'Removes all power icons from the character\'s power tray; preserves macros'),
    ('clear_petnames',  '', 'Clear the names of all your named pets'),
    ('clicktomove',  '', 'Enables click-to-move mode. Alias: /ctm'),
    ('cmdlist',  '', 'Prints out most slash commands in the chat window'),
    ('coalition',  'message', 'Spends the specified message on the Coalition channel. Alias: /c'),
    ('coalition_cancel',  'supergroup', 'Cancel coalition with a supergroup.'),
    ('coalition_invite',  'player', 'Invite player\'s supergroup to join coalition. Alias: /ci'),
    ('coalition_mintalkrank',  'rank', 'Sets the minimum rank of members of a coalition supergroup who your supergroup can hear.'),
    ('coalition_nosend',  '', 'Stop your supergroup from sending coalition chat to an ally supergroup.'),
    ('coalition_sg_mintalkrank',  'rank', 'Sets the minimum rank of members of your supergroup who can use coalition chat. Note: This command is currently non-functional.'),
    ('comment',  '', 'Set search comment'),
    ('compatiblecursors',  '', 'Enables useage of basic Windows mouse cursors instead of graphical cursors (command line option)'),
    ('copychat',  'tab', 'Copy the entire chat history from specified chat Tab into the clipboard'),
    ('costume_change',  'slot', 'Change costume to specified costume slot; opens the costume change window with no argument. Alias: /cc'),
    ('Cov',  '', 'Unknown.'),
    ('ctm',  '', 'Alias for /clicktomove'),
    ('ctmtoggle',  '', 'Toggles click-to-move mode'),
    ('cursorcache',  '', 'Enable cursor cache for smoother cursor changes'),
    ('demorecord',  'filename', 'Record a demo to the given name'),
    ('demostop',  '', 'Stop demo record/play'),
    ('demote',  'character', 'Demote supergroup member one rank'),
    ('dialog_answer',  'choice', 'Answer dialog with button matching the provided text choice (ok, yes, no, cancel, or accept)'),
    ('dialog_no',  '', 'Answer OK, No, or Cancel to current dialog'),
    ('dialog_yes',  '', 'Answer OK, Yes, or Accept to current dialog'),
    ('disable2d',  '', 'Disables 2D sprite drawing'),
    ('dofweight',  '', 'Sets DOF (Depth of Field) scale, valid values 0.0 - 2.0'),
    ('down',  '', 'Move down (if flying)'),
    ('e',  'emote', 'Emotes a text string or performs valid emote animation (Also: em or emote)'),
    ('e3screenshot',  '', 'Enables special e3 2004 screenshot mode'),
    ('em',  'emote', 'Emotes a text string or performs valid emote animation (Also: e or emote)'),
    ('emaildelete',  'number', 'Delete specified message'),
    ('emailsend',  'characters subject body', 'Send in-game email message'),
    ('emailsendattachment',  'Global Subject Infl AttachmentType InventoryLocation Message', 'Send message with attachment'),
    ('emote',  'emote', 'Emotes a text string or performs valid emote animation (Also: e or em)'),
    ('estrange',  'character', 'Remove character from friend list'),
    ('f',  'message', 'Send message to friends channel'),
    ('face',  '', 'Turn player to face target'),
    ('findmember',  '', 'Find a player'),
    ('first',  '', 'Toggles between first and third person camera'),
    ('fl',  '', 'Display friend list (Also: friendlist)'),
    ('follow',  '', 'Toggle follow mode (/cmdlist says that follow takes an argument (0 or 1), it does not)'),
    ('forward',  '', 'Move forward'),
    ('forward_mouse',  '', 'Move forward; enable autorun after 2 seconds'),
    ('friend',  'character', 'Add character to friend list'),
    ('friendlist',  '', 'Display friend list (Also: fl)'),
    ('fsaa',  '', 'Sets the amount of full screen antialiasing'),
    ('fullRelight',  '', 'Do not cap number of relit vertices per frame'),
    ('fullscreen',  '', 'Sets video mode to fullscreen'),
    ('g',  'message', 'Alias for /team'),
    ('gamereturn',  '', 'Leave fullscreen, close dialogs, and close non-essential windows. Alias: /window_close_extra'),
    ('getarenastats',  '', 'Get your arena stats'),
    ('get_comment',  '', 'Get search comment'),
    ('getglobalname',  'localname', 'Given the name of a character, this command will tell you the player\'s global name'),
    ('get_local_invite',  'globalname', 'Invite to team from globalname'),
    ('get_local_league_invite',  'globalname', 'Invite to league from globalname'),
    ('getlocalname',  'globalname', 'Given a global name, this command will tell you the name of a player\'s currently logged on character'),
    ('getpos',  '', 'Alias for /loc'),
    ('gfriend',  'name', 'Add player to your global friends list. Alias: /gfriend_player'),
    ('gfriend_player',  'name', 'Alias for /gfriend'),
    ('gfriends',  '', 'Display all members of your global friends list'),
    ('ghide',  '', 'Make yourself invisible to your global friends.'),
    ('gignore',  'username', 'Adds a player from your global ignore list.'),
    ('gignoring',  '', 'Lists the players on your global ignore list'),
    ('ginvite',  'channel_name username', 'Alias for /chan_invite'),
    ('ginvite_sg',  'channel_name rank', 'Alias for /chan_invite_sg'),
    ('gmotd',  '', 'View the global message again.'),
    ('goto_tray',  'number', 'Go to specified power tray number in the primary tray'),
    ('goto_tray_alt',  'number', 'Go to specified power tray number in the secondary tray'),
    ('goto_tray_alt2',  'number', 'Go to specified power tray number in the tertiary tray'),
    ('goto_trays_tray',  'position tray', 'Go to specified power tray number (1 to 10) in the given position.'),
    ('graphfps',  'number', 'Graph current framerate (1 = SWAP, 2 = GPU, 4 = CPU, 8 = SLI).'),
    ('group',  'message', 'Alias for /team'),
    ('guide',  'message', 'Alias for /help'),
    ('gunfriend',  'name', 'Remove player from global friends list. Alias: /gunfriend_player'),
    ('gunfriend_player',  'name', 'Alias for /gunfriend'),
    ('gunhide',  '', 'Make yourself visible to your global friends'),
    ('gunignore',  'username', 'Removes a player from your global ignore list.'),
    ('h',  'message', 'Alias for /help'),
    ('hc',  'message', 'Sends the specified message to the Help chat channel'),
    ('help',  'subject', 'Brings up the in-game Help Menu System.'),
    ('hide',  '', 'Opens the hide options dialog window (See Notes)'),
    ('hide_all',  '', 'Hides you completely from all other players, similar to the old /hide functionality'),
    ('hide_friends',  '', 'Hide from server friends'),
    ('hide_gchannels',  '', 'Hide from global chat channels'),
    ('hide_gfriends',  '', 'Hide from global friends'),
    ('hide_invite',  '', 'Block all invite requests'),
    ('hide_search',  '', 'Hide from searches'),
    ('hide_sg',  '', 'Hide from Super Group'),
    ('hide_tell',  '', 'Hide from tells (private messages)'),
    ('hideprimarychat',  '', 'Hide/unhide primary chat window text messages'),
    ('i',  'character', 'Alias for /invite'),
    ('incarnate_equip',  'Slot Power', 'Equips the specified Incarnate Ability. Does nothing if you don\'t have it or its slot is locked. Also does nothing if you or your teammates are in combat, if the currently equipped IA is recharging, or if it\'s been less than five minutes since that slot was last equipped. If there are spaces in the power name, then the power needs to be quoted or the spaces need to be replaced by underscores.'),
    ('incarnate_unequip',  'Slot Power', 'Unequips the specified Incarnate Ability. Does nothing if you don\'t have it or its slot is locked. Also does nothing if you or your teammates are in combat, if the currently equipped IA is recharging, or if it\'s been less than five minutes since that slot was last equipped. If there are spaces in the power name, then the power needs to be quoted or the spaces need to be replaced by underscores.'),
    ('incarnate_unequip_by_slot',  'Slot', 'Unequips whatever ability is in the specified Incarnate slot. Does nothing if the slot is locked or empty. Also does nothing if you or your teammates are in combat, if the currently equipped IA is recharging, or if it\'s been less than five minutes since that slot was last equipped.'),
    ('incarnate_unequip_all',  '', 'Unequips all equipped Incarnate Abilities.'),
    ('ignore',  'character', 'Ignore character'),
    ('ignore_spammer',  'character', 'Ignore character and sends alert to customer service'),
    ('ignorelist',  '', 'Displays a list of ignored characters'),
    ('info',  '', 'Opens the info window for the current target (yourself if you have no target).'),
    ('info_self',  '', 'Opens the info window for yourself'),
    ('info_self_tab',  'tab', 'Opens the specified tab of the info window for yourself'),
    ('info_tab',  'tab', 'Opens the specified tab of the info window for the current target (yourself if you have no target)'),
    ('inspexec_name',  'inspiration', 'Activate an inspiration by name'),
    ('inspexec_pet_name',  'inspiration petname', 'Gives an inspiration to the named pet'),
    ('inspexec_pet_target',  'petname', 'Gives an inspiration to the targeted pet'),
    ('inspexec_slot',  'number', 'Activate an inspiration slot in the first row (needs confirmation of possible options) Alias: /inspirationslot'),
    ('inspexec_tray',  'row column', 'Activate an inspiration slot in the given row and column'),
    ('inspirationslot',  '', 'Alias for /inspexec_slot'),
    ('insp_combine',  'inspiration inspiration', 'Combines three of a kind of first argument into one of the second argument. Example: /insp_combine "Insight" "Catch a Breath"'),
    ('insp_delete',  'inspiration', 'Deletes an inspiration. Example: /insp_delete "Catch a Breath"'),
    ('invite',  'character', 'Invite character to join team. Alias: /i'),
    ('k',  'character', 'Alias for /kick'),
    ('keybind_reset',  '', 'Alias for /unbind_all'),
    ('kick',  'character', 'Remove character from team. Alias: /k'),
    ('kiosk',  '', 'Pop up the kiosk info for the nearest kiosk if you\'re close enough'),
    ('l',  'message', 'Alias for /local'),
    ('lc',  'message', 'Alias for /league'),
    ('league',  'message', 'Sends the specified message on the League channel. Alias: /lc'),
    ('leaveteam',  '', 'Leave your current team'),
    ('left',  '', 'Strafe left'),
    ('lfg',  '', 'Toggle looking for group status'),
    ('lfgset',  'status', 'Sets your "looking for group" status. status is a parameter that indicates which status you wish to set and may be one of the following values. Setting the status to other values is undefined and may cause unexpected results.'),
    ('link_channel',  'ChannelName', 'Activates Context Menu for link channel name'),
    ('link_info',  'LinkName', 'Provides info window on matching link name'),
    ('link_interact',  '', 'Activates Context Menu for link name'),
    ('link_interact_global',  '', 'Activates Context Menu for link global name'),
    ('loc',  '', 'Get coordinates of current location on the map. Alias: /getpos'),
    ('local',  'message', 'Sends the specified message on the Local channel. Alias: /l'),
    ('localtime',  '', 'Prints local time (on your computer)'),
    ('logchat',  '', 'Toggle chat logging'),
    ('lookdown',  '', 'Pitch camera down'),
    ('lookup',  '', 'Pitch camera up'),
    ('lp',  '', 'Send message to your Level Pact channel.'),
    ('ma',  'message', 'Send message to the Architect Chat channel'),
    ('macro',  'name command', 'Add a macro to first empty slot'),
    ('macroslot',  'slot name command', 'Add a macro to specified slot'),
    ('makeleader',  'character', 'Change the team leader to targeted character, must have character targeted if no name is provided. Alias: /ml'),
    ('manage',  '', 'Go to the enhancement management screen'),
    ('map',  '', 'Toggles the map window'),
    ('maxColorTrackerVerts',  '', 'Maximum number of world object vertices to relight per frame'),
    ('maxfps',  '', 'Limits max frames per second.'),
    ('maximize',  '', 'Maximizes the window'),
    ('maxInactiveFps',  '', 'Limits max frames per second while the game is not in the foreground.'),
    ('maxrtframes',  'number', 'How many frames ahead to allow buffering.'),
    ('me',  '', 'Alias for /emote'),
    ('menu',  '', 'Toggles the menu'),
    ('missionmake',  '', 'Activate the My Arcs menu of Mission Search'),
    ('missionsearch',  '', 'Activate the mission search menu. Alias: /architect'),
    ('ml',  'character', 'Alias for /makeleader'),
    ('mmentry',  '', 'Choose between making and starting a mission maker story arc'),
    ('mouse_invert',  '', 'Invert meaning of mouseY for mouselook'),
    ('mouse_look',  '', 'Command key for mouselook'),
    ('mouse_speed',  '', 'Scale factor for mouse look'),
    ('myhandle',  '', 'Display your chat handle'),
    ('mypurchases',  '', 'Show the list of purchases you have access to'),
    ('namecaptain',  'name', 'Renames the \'Captain\' supergroup rank'),
    ('namecommander',  'name', 'Renames the \'Commander\' supergroup rank'),
    ('nameenforcer',  'name', 'Renames the \'Enforcer\' supergroup rank'),
    ('nameflunky',  'name', 'Renames the \'Flunky\' supergroup rank'),
    ('nameleader',  'name', 'Renames the \'Leader\' supergroup rank'),
    ('namelieutenant',  'name', 'Renames the \'Lieutenant\' supergroup rank'),
    ('namemember',  'name', 'Renames the \'Member\' supergroup rank'),
    ('nameoverlord',  'name', 'Renames the \'Overlord\' supergroup rank'),
    ('nameringleader',  'name', 'Renames the \'Ringleader\' supergroup rank'),
    ('nametaskmaster',  'name', 'Renames the \'Taskmaster\' supergroup rank'),
    ('nav',  '', 'Toggles the navigation window'),
    ('netgraph',  'int', 'Displays network connection information. Set int to 1 to enable, set to 0 to disable. You can also set it to 2 to see a large version.'),
    ('next_tray',  '', 'Go to next tray'),
    ('next_tray_alt',  '', 'Go to next secondary tray'),
    ('next_tray_alt2',  '', 'Go to next tertiary tray.'),
    ('next_trays_tray',  '', 'Go to next trays tray slot.'),
    ('nojumprepeat',  '', 'Disable jump auto-repeat'),
    ('norenderthread',  '', 'Tell the client to not use a separate thread for rendering graphics. (You\'re unlikely to want to do this.)'),
    ('nop',  '', 'Do nothing'),
    ('nosunflare',  '', 'Disables sun flare for performance debugging'),
    ('option_save',  '', 'Saves a list of option settings to COH_INSTALL_DIRECTORY\\data\\options.txt'),
    ('option_save_file',  'filename', 'Saves a list of option settings to a file'),
    ('option_load',  '', 'Reads a list of option settings from COH_INSTALL_DIRECTORY\\data\\options.txt'),
    ('option_load_file',  'filename', 'Reads a list of option settings from a file'),
    ('option_set',  'optionname value', 'Sets an option setting'),
    ('option_toggle',  'optionname', 'Toggles an option setting. (This command is currently bugged and can cause the client to crash)'),
    ('option_list',  '', 'Lists names allowed for /option_set and /option_toggle'),
    ('p',  'character message', 'Alias for /tell'),
    ('petcom',  'commands', 'Sends commands to your current pet.'),
    ('petcom_all',  'commands', 'Sends commands to all pets.'),
    ('petcom_name',  'pet_name commands', 'Sends commands to named pet.'),
    ('petcom_pow',  'power_name commands', 'Sends commands to pets summoned by named power.'),
    ('petition',  'message', 'Sends in-game user petition to customer support'),
    ('petoptions',  '', 'Displays pet option context menu'),
    ('petrename',  'name', 'Rename your current pet'),
    ('petrename_name',  'name', 'Rename the named pet'),
    ('petsay',  'message', 'Current pet says the message'),
    ('petsay_all',  'message', 'All pets say the message'),
    ('petsay_name',  'pet_name message', 'Named pet says the message'),
    ('petsay_pow',  'power_name message', 'Pets summoned by named power says the message'),
    ('pet_select',  'integer', 'Selects a pet from the list, starting with 0 at the top'),
    ('pet_select_name',  'pet_name', 'Selects the named pet'),
    ('playernote',  'name', 'Opens note window for a given global playername'),
    ('playerturn',  '', 'Turn player to match camera'),
    ('popmenu',  'name', 'Opens a custom pop-up menu at the cursor\'s location'),
    ('powers',  '', 'Toggles the power inventory display'),
    ('powexec_abort',  '', 'Cancels the auto-attack power and the queued power'),
    ('powexec_alt2slot',  'slot', 'Executes the given power slot from the second alternate tray'),
    ('powexec_altslot',  'slot', 'Executes the given power slot from the alternate tray'),
    ('powexec_auto',  'power', 'Sets the auto-attack power to given named power (or blank to shut it off, or toggles if it\'s on already)'),
    ('powexec_name',  'power', 'Executes a power with the given name'),
    ('powexec_server_slot',  'slot', 'Executes the given power slot from the server-controlled tray.'),
    ('powexec_slot',  'slot', 'Executes the given power slot from the current tray'),
    ('powexec_toggleoff',  'power', 'Toggles a given power off. If it\'s already off, does nothing'),
    ('powexec_toggleon',  'power', 'Toggles a given power on. If it\'s already on, does nothing'),
    ('powexec_tray',  'slot tray', 'Executes a power in the given tray and slot'),
    ('powexec_unqueue',  '', 'Cancels the currently queued power'),
    ('prev_tray',  '', 'Go to previous tray'),
    ('prev_tray_alt',  '', 'Go to previous secondary tray'),
    ('prev_tray_alt2',  '', 'Go to previous tertiary tray.'),
    ('prev_trays_tray',  '', 'Go to previous trays tray slot.'),
    ('priorityBoost',  'number', 'Set the game process priority to Above Normal rather than Normal when running in the foreground.'),
    ('private',  'character message', 'Alias for /tell'),
    ('profiler_record',  'file', 'Record client profiler information to specified file.'),
    ('profiler_stop',  '', 'Stop recording profiler information.'),
    ('promote',  'character', 'Promote supergroup member one rank'),
    ('quickchat',  '', 'Pops up the quickchat menu'),
    ('quit',  '', 'Quits game'),
    ('quittocharacterselect',  '', 'Quits to character select'),
    ('quittologin',  '', 'Quits to login screen'),
    ('raid_invite',  '', 'Alias for /sgraid_invite'),
    ('release',  '', 'Activate medicom unit for emergency medical transport when defeated'),
    ('release_pets',  '', 'Release your current pets'),
    ('reloadgfx',  '', 'Unloads all textures (causing them to be reloaded dynamically)'),
    ('renderscale',  '', 'Changes the scale at which the 3D world is rendered relative to your screen size'),
    ('renderscalefilter',  '', 'Changes method of filtering used in renderscaling'),
    ('renderscalex',  '', 'Changes the horizontal scale at which the 3D world is rendered relative to your screen size'),
    ('renderscaley',  '', 'Changes the vertical scale at which the 3D world is rendered relative to your screen size'),
    ('rendersize',  '', 'Changes the size at which the 3D world is rendered'),
    ('renderthread',  '', 'Tell the client to use a separate thread for rendering graphics. (Unneeded as of i11.)'),
    ('reply',  'message', 'Sends message to the last person who sent you a tell'),
    ('req',  'message', 'Alias for /request'),
    ('request',  'message', 'Send message to Request channel. Alias: /req'),
    ('requestexitmission',  'number', 'Leave the mission once it is completed. It requires a number argument, but the number doesn\'t seem to do anything. This command does not appear on the /cmdlist.'),
    ('respec',  '', 'Go to the power respecification screen if you have a free respec'),
    ('right',  '', 'Strafe right'),
    ('s',  'message', 'Alias for /say'),
    ('say',  'message', 'Sends the given text on the current chat channel. Alias: /s'),
    ('screen',  'resolution', 'Sets X and Y screen dimensions, should be constrained to 640x480,1024x768, 1280x1024, 1600x1200, etc.'),
    ('screenshot',  '', 'Save a .jpg format screenshot'),
    ('screenshottga',  '', 'Save a .tga format screenshot'),
    ('screenshottitle',  'title', 'Save a .jpg format screenshot with the given title.'),
    ('screenshotui',  'boolean', 'Show ui in screenshots'),
    ('sea',  'character', 'Alias for /search'),
    ('search',  'character', 'Find a character. Alias: /sea'),
    ('sell',  'message', 'Send message to the Auction channel'),
    ('send',  'channel message', 'Send message to specified global chat channel'),
    ('servertime',  '', 'Print the current server time'),
    ('set_title',  'number', 'Set badge title by number, if you do not have the specified badge your current badge title will be cleared'),
    ('sg',  'message', 'Alias for /supergroup'),
    ('sgi',  'character', 'Alias for /sginvite'),
    ('sginvite',  'character', 'Invite character to join supergroup. Alias: /sgi'),
    ('sgk',  'character', 'Alias for /sgkick'),
    ('sgkick',  'character', 'Kick character from supergroup. Alias: /sgk'),
    ('sgleave',  '', 'Leave the current supergroup.'),
    ('sgmode',  '', 'Toggle supergroup mode.'),
    ('sgmodeset',  'mode', 'Set Supergroup mode. 0 leave 1 enter'),
    ('sgraid_invite',  'player', 'Invite player\'s supergroup to an instant raid. Alias: /raid_invite'),
    ('sgraid_window',  'daybits hour', 'Sets your supergroup raid window.'),
    ('sgsetdemotetimeout',  'days', 'Sets the number of days a leader in your supergroup has to go without logging in before the leader is demoted. Note: This command is currently non-functional.'),
    ('sgsetdescription',  'description', 'Sets your supergroup description.'),
    ('sgsetmotd',  'message', 'Sets the supergroup\'s message of the day.'),
    ('sgsetmotto',  'motto', 'Sets the supergroup\'s motto.'),
    ('sgstats',  '', 'Display supergroup info in chat window. Note: This command is currently non-functional.'),
    ('shaderdetail',  '', 'Changes the shader detail level'),
    ('shadowvol',  'boolean', 'Controls whether or not shadow volumes are drawn'),
    ('show',  '', 'Forces the given window to be shown. Alias: /window_show'),
    ('show_bind',  'key', 'Shows bind attached to specified key'),
    ('showfps',  'boolean', 'Show current framerate'),
    ('show_petnames',  '', 'Displays the names of all your named pets'),
    ('slashchat',  '', 'Starts chat-entry mode with slash'),
    ('sliClear',  'number', 'Clear each FBO the first time it is used in the frame to help SLI/CF (0 to disable).'),
    ('sliFBOs',  'number', 'Number of SLI/CF framebuffers to allocate (1 to disable).'),
    ('sliLimit',  'number', 'Limit number of SLI/CF frames to allow in parallel (0 to disable limiter).'),
    ('speed_turn',  'number', 'Set the number of degrees for rotateleft/right'),
    ('ss',  'boolean', 'Controls whether or not simple shadows are drawn'),
    ('startchat',  '', 'Starts chat-entry mode'),
    ('stopinactivedisplay',  '', 'Stops rendering when the game is not the foreground application'),
    ('stuck',  '', 'Try to get unstuck if you are stuck in the geometry.'),
    ('sync',  '', 'Try to get back in sync if you are out of sync with the server.'),
    ('synch',  '', 'Alias for /sync'),
    ('supergroup',  'message', 'Sends the specified message to the Supergroup channel. Alias: /sg'),
    ('suppressCloseFx',  '', 'Hide all personal FX when the camera is closer than the suppressCloseFxDist'),
    ('suppressCloseFxDist',  'number', 'Within this camera distance, personal FX will be suppressed.'),
    ('t',  'name message', 'Alias for /tell'),
    ('tabglobalnext',  '', 'Cycle forward through all chat tabs in all windows, will open the corresponding chat window if necessary'),
    ('tabglobalprev',  '', 'Cycle backward through all chat tabs in all windows, will open the corresponding chat window if necessary'),
    ('tabnext',  'window', 'Cycle forward through all chat tabs in specified chat window'),
    ('tabprev',  'window', 'Cycle backward through all chat tabs in specified chat window'),
    ('tabselect',  'tab', 'Select the given chat tab, will open the corresponding chat window if necessary'),
    ('tabtoggle',  '', 'Make the previously active chat tab the new active tab'),
    ('target',  '', 'Toggles the target window'),
    ('target_custom_far',  'params', 'Targets furthest matching target using the same parameters as used by /target_custom_next.'),
    ('target_custom_near',  'params', 'Targets nearest matching target using the same parameters as used by /target_custom_next.'),
    ('target_custom_next',  'params',   'Cycles through matching targets in near to far order using the following parameters.\n'+
                                        'enemy Hostile enemies.\n '+
                                        'friend	Friendlies (including pets).\n '+
                                        'defeated	0 HP targets.\n '+
                                        'alive	Living targets.\n '+
                                        'mypet	Include only your pets.\n '+
                                        'notmypet	Exclude your pets.\n '+
                                        'base	Include only passive base items.\n '+
                                        'notbase	Exclude passive base items.\n '+
                                        'teammate	Include only teammates.\n '+
                                        'notteammate	Exclude teammates.\n '
                                        'anything else	Matches against name for specific targeting'),
    ('target_custom_prev',  'params', 'Cycles through matching targets in far to near order using the same parameters as used by /target_custom_next.'),
    ('target_enemy_far',  '', 'Targets the farthest enemy'),
    ('target_enemy_near',  '', 'Targets the nearest enemy'),
    ('target_enemy_next',  '', 'Cycles through visible targetable enemies in near to far order'),
    ('target_enemy_prev',  '', 'Cycles through visible targetable enemies in far to near order'),
    ('target_friend_far',  '', 'Targets the farthest friend'),
    ('target_friend_near',  '', 'Targets the nearest friend'),
    ('target_friend_next',  '', 'Cycles through visible targetable friends in near to far order'),
    ('target_friend_prev',  '', 'Cycles through visible targetable friends in far to near order'),
    ('target_name',  'name', 'Targets next entity that matches the given name.'),
    ('team',  'message', 'Send message on the Team channel. Aliases: /g, /group'),
    ('team_select',  'number', 'Select specified Team member'),
    ('tell',  'name, message', 'Sends a private message to a specific player. If name is a character name, the message will fail unless the player is online. If name is a global name, the message will be delivered the next time that player is online. Note that the comma after name is required or the command will fail. Aliases: /t, /p, /private, /whisper'),
    ('tell_last',  'message', 'Sends a tell to the last player you sent a tell to. Alias: /tl'),
    ('texaniso',  '', 'Sets the amount of anisotropic filtering to use, reloads textures'),
    ('texwordeditor',  '', 'Edit the text layout for translatable textures'),
    ('third',  '', 'Toggles between first and third person camera'),
    ('title_change',  '', 'players can now change their titles'),
    ('tl',  'message', 'Alias for /tell_last'),
    ('tll',  'message', 'Send a message to the league leader.'),
    ('toggle_enemy_prev',  '', 'Cycles through targetable enemies in reverse order'),
    ('toggle_enemy',  '', 'Cycles through targetable enemies starting with the closest'),
    ('toggle',  '', 'Show a window if hidden, hide a window if shown. Alias: /window_toggle'),
    ('trade',  'character', 'Invite character to trade, must have character targeted if no name is provided'),
    ('tray',  '', 'Toggles the tray window'),
    ('tray_sticky',  'position state', 'Set the sticky-state of the specified tray. 0 removes stickiness, anything else adds it.'),
    ('tray_sticky_alt2',  '', 'Toggle the sticky-state of the alt2 tray.'),
    ('ttl',  'message', 'Send a message to the team leader.'),
    ('turnleft',  'degrees', 'Rotate left a fixed number of degrees'),
    ('turnright',  'degrees', 'Rotate right a fixed number of degrees'),
    ('uiskin',  '', 'Unknown'),
    ('unbind',  'keyname', 'Unbinds a bound key (sets it to default). If the default action is not desired, use: /bind keyname "nop"'),
    ('unbind_all',  '', 'Resets keybinds, returning all keys to their default bindings.'),
    ('unfriend',  'character', 'Remove character from friends list'),
    ('unhide',  '', 'Opens the hide options dialog window'),
    ('unhide_all',  '', 'Stop hiding from all other players and allow them to see whether you are online'),
    ('unhide_friends',  '', 'Stop hiding from server friends'),
    ('unhide_gchannels',  '', 'Stop hiding from global chat channels'),
    ('unhide_gfriends',  '', 'Stop hiding from global friends'),
    ('unhide_invite',  '', 'Stop blocking invite requests'),
    ('unhide_search',  '', 'Stop hiding from searches'),
    ('unhide_sg',  '', 'Stop hiding from Super Group'),
    ('unhide_tell',  '', 'Stop hiding from tells (private messages)'),
    ('unignore',  'character', 'Unignore character'),
    ('unlevelingpact',  '', 'Bring up the dialog for quitting a leveling pact.'),
    ('unselect',  '', 'Unselects currently selected thing'),
    ('up',  '', 'Jump or fly up'),
    ('usebumpmaps',  '', 'Use bumpmaps'),
    ('useCubemap',  'number', 'Use cubemap'),
    ('usedof',  '', 'Use Depth of Field effects if available'),
    ('usenvfence',  'number', 'Use NV fences instead of ARB queries.'),
    ('usefp',  '', 'Use a floating point render target for HDR lighting effects if available'),
    ('usehdr',  '', 'Use HDR lighting effects (Bloom/tonemapping) if available'),
    ('useHQ',  'number', 'Allow use of High Quality shader variants'),
    ('useNewColorPicker',  '', 'Use new color picker in editor.'),
    ('userenderscale',  '', 'Enables/disables render scaling feature'),
    ('usewater',  '', 'Use fancy water effects if available'),
    ('vault',  '', 'Activate the personal storage Menu'),
    ('vis_scale',  'distance', 'Controls draw distance (1.0=default)'),
    ('watching',  '', 'List all channels that you belong to'),
    ('wdw_load',  '', 'Reads a list of window settings from COH_INSTALL_DIRECTORY\\wdw.txt'),
    ('wdw_load_file',  'filename', 'Reads a list of window settings from a file'),
    ('wdw_save',  '', 'Saves a list of window settings to COH_INSTALL_DIRECTORY\\wdw.txt'),
    ('wdw_save_file',  'filename', 'Saves a list of window settings to a file'),
    ('wentworths',  '', 'Activate the Auction House Menu Alias: /auctionhouse'),
    ('whereami',  '', 'Tells the name of the map you are on'),
    ('whisper',  'name, message', 'Alias for /tell'),
    ('who',  '', 'Brings up the find player window; with argument, searches for players matching the argument in the current zone'),
    ('whoall',  '', 'Shows who is on the current map'),
    ('window_close_extra',  '', 'Alias for /gamereturn'),
    ('window_color',  '', 'Changes the window colors'),
    ('window_hide',  '', 'Forces the given window to be hidden. (See Notes)'),
    ('window_names',  '', 'Lists the names of all windows'),
    ('window_resetall',  '', 'Resets all window locations, sizes, and visibility to their defaults.'),
    ('window_scale',  '', 'Change a single window scale.'),
    ('window_show',  '', 'Forces the given window to be shown. Alias: /show'),
    ('window_toggle',  '', 'Show a window if hidden, hide a window if shown. Alias: /toggle'),
    ('y',  'message', 'Alias for /broadcast'),
    ('yell',  'message', 'Alias for /broadcast'),
    ('zoomin',  '', 'Zoom camera in'),
    ('zoomout',  '', 'Zoom camera out')
]